/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthMfaRouteImport } from './routes/auth.mfa'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppResumesRouteImport } from './routes/_app.resumes'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppJobTrackerRouteImport } from './routes/_app.job-tracker'
import { Route as AppInterviewsRouteImport } from './routes/_app.interviews'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCoverLettersRouteImport } from './routes/_app.cover-letters'
import { Route as AppAtsRouteImport } from './routes/_app.ats'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppResumesIdRouteImport } from './routes/_app.resumes.$id'
import { Route as AppInterviewsIdRouteImport } from './routes/_app.interviews.$id'
import { Route as AppAtsIdRouteImport } from './routes/_app.ats.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppResumesRoute = AppResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppJobTrackerRoute = AppJobTrackerRouteImport.update({
  id: '/job-tracker',
  path: '/job-tracker',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsRoute = AppInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoverLettersRoute = AppCoverLettersRouteImport.update({
  id: '/cover-letters',
  path: '/cover-letters',
  getParentRoute: () => AppRoute,
} as any)
const AppAtsRoute = AppAtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesIdRoute = AppResumesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppResumesRoute,
} as any)
const AppInterviewsIdRoute = AppInterviewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInterviewsRoute,
} as any)
const AppAtsIdRoute = AppAtsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAtsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRoute
  '/ats': typeof AppAtsRouteWithChildren
  '/cover-letters': typeof AppCoverLettersRoute
  '/dashboard': typeof AppDashboardRoute
  '/interviews': typeof AppInterviewsRouteWithChildren
  '/job-tracker': typeof AppJobTrackerRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/resumes': typeof AppResumesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/signup': typeof AuthSignupRoute
  '/ats/$id': typeof AppAtsIdRoute
  '/interviews/$id': typeof AppInterviewsIdRoute
  '/resumes/$id': typeof AppResumesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRoute
  '/ats': typeof AppAtsRouteWithChildren
  '/cover-letters': typeof AppCoverLettersRoute
  '/dashboard': typeof AppDashboardRoute
  '/interviews': typeof AppInterviewsRouteWithChildren
  '/job-tracker': typeof AppJobTrackerRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/resumes': typeof AppResumesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/signup': typeof AuthSignupRoute
  '/ats/$id': typeof AppAtsIdRoute
  '/interviews/$id': typeof AppInterviewsIdRoute
  '/resumes/$id': typeof AppResumesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/ats': typeof AppAtsRouteWithChildren
  '/_app/cover-letters': typeof AppCoverLettersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/interviews': typeof AppInterviewsRouteWithChildren
  '/_app/job-tracker': typeof AppJobTrackerRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/resumes': typeof AppResumesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_app/ats/$id': typeof AppAtsIdRoute
  '/_app/interviews/$id': typeof AppInterviewsIdRoute
  '/_app/resumes/$id': typeof AppResumesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/ats'
    | '/cover-letters'
    | '/dashboard'
    | '/interviews'
    | '/job-tracker'
    | '/notifications'
    | '/profile'
    | '/resumes'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/signup'
    | '/ats/$id'
    | '/interviews/$id'
    | '/resumes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/ats'
    | '/cover-letters'
    | '/dashboard'
    | '/interviews'
    | '/job-tracker'
    | '/notifications'
    | '/profile'
    | '/resumes'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/signup'
    | '/ats/$id'
    | '/interviews/$id'
    | '/resumes/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/sitemap.xml'
    | '/_app/admin'
    | '/_app/ats'
    | '/_app/cover-letters'
    | '/_app/dashboard'
    | '/_app/interviews'
    | '/_app/job-tracker'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/resumes'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/signup'
    | '/_app/ats/$id'
    | '/_app/interviews/$id'
    | '/_app/resumes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/mfa': {
      id: '/auth/mfa'
      path: '/mfa'
      fullPath: '/auth/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/resumes': {
      id: '/_app/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof AppResumesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/job-tracker': {
      id: '/_app/job-tracker'
      path: '/job-tracker'
      fullPath: '/job-tracker'
      preLoaderRoute: typeof AppJobTrackerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews': {
      id: '/_app/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AppInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cover-letters': {
      id: '/_app/cover-letters'
      path: '/cover-letters'
      fullPath: '/cover-letters'
      preLoaderRoute: typeof AppCoverLettersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ats': {
      id: '/_app/ats'
      path: '/ats'
      fullPath: '/ats'
      preLoaderRoute: typeof AppAtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes/$id': {
      id: '/_app/resumes/$id'
      path: '/$id'
      fullPath: '/resumes/$id'
      preLoaderRoute: typeof AppResumesIdRouteImport
      parentRoute: typeof AppResumesRoute
    }
    '/_app/interviews/$id': {
      id: '/_app/interviews/$id'
      path: '/$id'
      fullPath: '/interviews/$id'
      preLoaderRoute: typeof AppInterviewsIdRouteImport
      parentRoute: typeof AppInterviewsRoute
    }
    '/_app/ats/$id': {
      id: '/_app/ats/$id'
      path: '/$id'
      fullPath: '/ats/$id'
      preLoaderRoute: typeof AppAtsIdRouteImport
      parentRoute: typeof AppAtsRoute
    }
  }
}

interface AppAtsRouteChildren {
  AppAtsIdRoute: typeof AppAtsIdRoute
}

const AppAtsRouteChildren: AppAtsRouteChildren = {
  AppAtsIdRoute: AppAtsIdRoute,
}

const AppAtsRouteWithChildren =
  AppAtsRoute._addFileChildren(AppAtsRouteChildren)

interface AppInterviewsRouteChildren {
  AppInterviewsIdRoute: typeof AppInterviewsIdRoute
}

const AppInterviewsRouteChildren: AppInterviewsRouteChildren = {
  AppInterviewsIdRoute: AppInterviewsIdRoute,
}

const AppInterviewsRouteWithChildren = AppInterviewsRoute._addFileChildren(
  AppInterviewsRouteChildren,
)

interface AppResumesRouteChildren {
  AppResumesIdRoute: typeof AppResumesIdRoute
}

const AppResumesRouteChildren: AppResumesRouteChildren = {
  AppResumesIdRoute: AppResumesIdRoute,
}

const AppResumesRouteWithChildren = AppResumesRoute._addFileChildren(
  AppResumesRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAtsRoute: typeof AppAtsRouteWithChildren
  AppCoverLettersRoute: typeof AppCoverLettersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInterviewsRoute: typeof AppInterviewsRouteWithChildren
  AppJobTrackerRoute: typeof AppJobTrackerRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppResumesRoute: typeof AppResumesRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAtsRoute: AppAtsRouteWithChildren,
  AppCoverLettersRoute: AppCoverLettersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInterviewsRoute: AppInterviewsRouteWithChildren,
  AppJobTrackerRoute: AppJobTrackerRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppResumesRoute: AppResumesRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMfaRoute: typeof AuthMfaRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthMfaRoute: AuthMfaRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
